Start implementing pull-requests-gen

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -426,8 +426,8 @@ EOF
 }
 
 pull_requests_prep() {
-    crowbar_is_clean && fetch_all && sync_everything && backup_everything || \
-	die "Unable to prepare for pull requests"
+    #crowbar_is_clean && fetch_all && sync_everything && backup_everything || \
+    #	die "Unable to prepare for pull requests"
     local -A barclamps_to_push
     local -a branches_to_push
     local branch bc
@@ -459,8 +459,42 @@ pull_requests_prep() {
     [[ ${branches_to_push} ]] && \
 	echo -n " --branches ${branches_to_push[@]}"
     [[ ${!barclamps_to_push[*]} ]] && \
-	echo -n " --barclamps ${!barclamps_to_push[@]}"
+	echo -n " --barclamps ${!barclamps_to_push[@]#barclamps/}"
     echo
+}
+
+pull_requests_gen() {
+    # $@ = options to parse
+    local -A barclamps pull_requests
+    local -a branches
+    local bc br title body option
+    for option in "$@"; do
+	case $option in
+	    --branches) 
+		shift
+		while [[ $1 != '--'* ]]; do
+		    br="$1"
+		    shift
+		    in_repo branch_exists "$1" || \
+			die "$br is not a branch in Crowbar!"
+		    is_in "$1" "${branches[*]}" || branches+="$1"
+		done;;
+	    --barclamps)
+		shift
+		while [[ $1 != '--'* ]]; do
+		    bc="${1%%/*}"
+		    br="${1#*/}"
+		    [[ $bc = $br ]] && br="master"
+		    shift
+		    is_barclamp "$bc" || die "$bc is not a barclamp!"
+		    in_barclamp "$bc" branch_exists "$br" || \
+			die "$br is not a branch in barclamp $bc!"
+		    barclamps["$bc/$br"]="unclassified"
+		done;;
+	    *) die "Unknown option $1 to $0 pull-requests-gen!";;
+	esac
+    done
+    die "pull-requests-gen: Not implimented yet."
 }
 
 push_branches() {
@@ -488,7 +522,7 @@ case $1 in
     backup) backup_everything;;
     push) shift; push_branches "$@";;
     pull-requests-prep) pull_requests_prep;;
-    pull-requests-gen) die "$1 is not implemented yet.";;
+    pull-requests-gen) shift; pull_requests_gen "$@";;
     help) dev_help;;
     *) die "Unknown command $1.  Please use \"help\" for help.";;
 esac
