Fix several bugs around using build_branch and release_branch inappropriatly

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -1160,7 +1160,7 @@ __pin_release() {
 	done
     elif release_exists "$1"; then
 	for build in $(builds_in_release "$1"); do
-	    __pin_release "$build" "$2" || return 1
+	    __pin_release "$1/$build" "$2" || return 1
 	done
     else
 	echo "Don't know what $1 is!" >&2
@@ -1219,9 +1219,10 @@ find_unsynced_branches_for_release() {
 	local branches=()
         local from to br
         for build in "${builds[@]}"; do
-            ref=$(barclamp_branch_for_build "$build" "$bc")
+            barclamp_exists_in_build "$rel/$build/$bc" || continue
+            ref=$(barclamp_branch_for_build "$rel/$build" "$bc")
             [[ $ref = empty-branch ]] && \
-                die "Barclamp $bc should exist for $build, but it is set to empty-branch!"
+                die "Barclamp $bc should exist for $rel/$build, but it is set to empty-branch!"
             break
         done
 	upstream="$(in_barclamp "$bc" remote_for_branch "$ref")" || continue
@@ -1301,28 +1302,29 @@ merge_or_rebase_from_remote() {
 # Handle merges across releases.
 merge_releases() {
     # $@ = releases to merge.
-    local rel branch start_ref
+    local rel branch start_ref build bc
+    bc="${repo##*/}"
     start_ref=$(git rev-parse HEAD)
     for rel in "$@"; do
 	[[ $rel ]] || continue
 	[[ $rel = $(current_release) ]] &&  continue
 	release_exists "$rel" || continue
-	branch=$(release_branch "$rel")
-	branch_exists "$branch" || continue
-	git merge -q "$branch" && continue
-	git merge --abort
-	{
-            echo "Barclamp ${repo##*/}:"
-	    echo "  Merging releases $@ into $(current_release) failed."
-	    echo "  Dropping to a shell for you to fix up."
-	    echo "  If you want to abort this merge, exit the shell with 'exit 1'"
-	    /bin/bash
-	} || {
+        for branch in $(barclamp_branches_for_release "$rel" "$bc"); do
+	    git merge -q "$branch" && continue
 	    git merge --abort
-	    git branch "${head#refs/heads/}" "$start_ref"
-	    debug "Barclamp ${repo##*/}: Merge of $br from $rel into $cur_rel failed."
-            return 1
-	}
+	    {
+                echo "Barclamp ${repo##*/}:"
+	        echo "  Merging releases $@ into $(current_release) failed."
+	        echo "  Dropping to a shell for you to fix up."
+	        echo "  If you want to abort this merge, exit the shell with 'exit 1'"
+	        /bin/bash
+	    } || {
+	        git merge --abort
+	        git branch "${head#refs/heads/}" "$start_ref"
+	        debug "Barclamp ${repo##*/}: Merge of $br from $rel into $cur_rel failed."
+                return 1
+	    }
+        done
     done
 }
 
@@ -1477,8 +1479,9 @@ branch_needs_pull_req() {
 # This function tries to ensure that it will fail without doing anything
 # if there will be any problems (due to authetication or whatever).
 push_release() {
-    local release remotes remote bc res cmd
+    local rel_br release remotes remote bc res cmd build
     local pushcmds=()
+    local -A branches
     release="$(current_release)" remotes=("$(origin_remote)")
     [[ $DEV_TO_REMOTES ]] && remotes=("${DEV_TO_REMOTES[@]}")
     if [[ $1 ]]; then
@@ -1486,7 +1489,6 @@ push_release() {
             die "Cannot push non-existent local release $1"
         release="$1"
     fi
-    local rel_br="$(release_branch "$release")"
     local can_push=true
     for remote in "${remotes[@]}"; do
         remote_available "$remote" && continue
@@ -1494,24 +1496,28 @@ push_release() {
     done
     debug "Testing push of $release to ${remotes[*]}:"
     for bc in $(barclamps_in_release "$release"); do
-        in_barclamp "$bc" branch_exists "$rel_br" || \
-            die "Barclamp $bc is in release $br, bit to does not have release branch $rel_br!" \
-            "Aborting."
+        for rel_br in $(barclamp_branches_for_release "$release" "$bc"); do
+            branches["$bc:$rel_br"]="$bc"
+        done
         local found_one_remote=false
         for remote in "${remotes[@]}"; do
             in_barclamp "$bc" git_remote_exists "$remote" || continue
             found_one_remote=true
-            if res="$(in_barclamp "$bc" git_push -nq "$remote" -- "${rel_br}:${rel_br}")"; then
-                pushcmds+=("in_barclamp \"$bc\" git_push \"$remote\" -- \"${rel_br}:${rel_br}\"")
-                continue
-            fi
-            debug "Barclamp $bc: Push of $rel_br to $remote will fail:"
-            echo "$res" >&2
-            echo >&2
-            can_push=false
         done
         [[ $found_one_remote = true ]] && continue
         die "No remotes have $bc available.  Aborting."
+    done
+    for rel_br in "${!branches[@]}"; do
+        bc=${rel_br%%:*}
+        rel_br=${rel_br#*:}
+        if res="$(in_barclamp "$bc" git_push -nq "$remote" -- "${rel_br}:${rel_br}")"; then
+            pushcmds+=("in_barclamp \"$bc\" git_push \"$remote\" -- \"${rel_br}:${rel_br}\"")
+            continue
+        fi
+        debug "Barclamp $bc: Push of $rel_br to $remote will fail:"
+        echo "$res" >&2
+        echo >&2
+        can_push=false
     done
     [[ $can_push = false ]] && exit 1
     debug "Test passed, pushing branches."
@@ -1535,11 +1541,12 @@ pull_requests_prep() {
     [[ $DEV_TO_REMOTES ]] && to_remote="$DEV_TO_REMOTES"
     remote_is_github "$to_remote" || \
 	die "Cannot issue pull requests for $to_remote, it is not from github."
-    local branch bc
-    branch=$(release_branch "$(current_release)")
-    for bc in $(barclamps_in_release $(current_release)); do
-	in_barclamp "$bc" branch_needs_pull_req "$branch" || continue
-	barclamps_to_push+=("$bc/$branch")
+    local branch bc build release=$(current_release)
+    for bc in $(barclamps_in_release $release); do
+        for branch in $(barclamp_branches_for_release "$release" "$bc"); do
+	    in_barclamp "$bc" branch_needs_pull_req "$branch" || continue
+	    barclamps_to_push+=("$bc/$branch")
+        done
     done
     [[ ${push_master} || ${barclamps_to_push} ]] || {
 	echo "Everything up to date, no pull requests are possible."
@@ -1661,8 +1668,6 @@ pull_requests_gen() {
 		    shift
 		    in_barclamp "$bc" branch_exists "$br" || \
 			die "$br is not a branch in barclamp $bc!"
-		    [[ $br = *master ]] || \
-			die "Non-master branch for a barclamp passed.  Not valid for now."
 		    in_barclamp "$bc" git_remote_exists "$to_remote" || \
 			die "Cannot make pull request from barclamp $bc -- it is not present at remote $to_remote!"
 		    barclamps["$bc"]="true"
@@ -1764,6 +1769,22 @@ barclamp_branch_for_build() {
         echo "$3" > "$bcfile"
         git add "$bcfile"
     fi
+}
+
+barclamp_branches_for_release() {
+    # $1 = release
+    # $2 = barclamp
+    local -A branches
+    local build br
+    release_exists "$1" || die "$1 is not a release!"
+    for build in $(builds_for_barclamp_in_release "$2" "$1"); do
+        br=$(barclamp_branch_for_build "$1/$build" "$2")
+        [[ $br && $br != empty-branch ]] || continue
+        branches[$br]="$br"
+    done
+    for br in "${branches[@]}"; do
+        echo "$br"
+    done
 }
 
 refs_for_build() {
@@ -2001,7 +2022,7 @@ reset_branch() {
 # or the current upstream version.
 reset_release() {
     barclamps_are_clean || exit 1
-    local target_release=$(current_release) target=backup
+    local target_release=$(current_release) target=backup build
     local -A barclamp_targets
     while [[ $1 ]]; do
 	case $1 in
@@ -2017,31 +2038,31 @@ reset_release() {
 	remote_available personal && remote_is_github personal || \
 	    die "No personal remote available at Github.  Cannot restore from backup."
     fi
-    target_branch=$(release_branch $target_release)
     for bc in $(barclamps_for_release "$target_release"); do
 	[[ -d $CROWBAR_DIR/barclamps/$bc/.git || \
 	    -f $CROWBAR_DIR/barclamps/$bc/.git ]] || continue
-	in_barclamp "$bc" branch_exists "$target_branch" || continue
-	case $target in
-	    upstream) barclamp_targets[$bc]="$(in_barclamp "$bc" remote_for_branch "$target_branch")/$target_branch" || \
-		die "No tracking branch for $br in $bc, cannot restore from backup.";;
-	    backup) barclamp_targets[$bc]+="personal/$target_branch";;
-	    *) die "Don't know how to reset barclamp $bc to $target_method";;
-	esac
-	if ! in_barclamp "$bc" git rev-parse --quiet --verify \
-	    "${barclamp_targets[$bc]}" &>/dev/null; then
-	    if [[ $target = backup ]]; then
-		debug "${barclamps[$bc]} in $bc has never been backed up, skipping."
-		unset barclamps_targets[$bc]
-	    elif [[ $target = upstream ]]; then
-		debug "Cannot reset barclamp $bc to ${barclamp_targets[$bc]}"
-		unset barclamps_targets[$bc]
+        for target_branch in $(barclamp_branches_for_release "$target_release" "$bc"); do
+	    case $target in
+	        upstream) barclamp_targets[$bc:$target_branch]="$(in_barclamp "$bc" remote_for_branch "$target_branch")/$target_branch" || \
+		    die "No tracking branch for $br in $bc, cannot restore from backup.";;
+	        backup) barclamp_targets[$bc:$target_branch]+="personal/$target_branch";;
+	        *) die "Don't know how to reset barclamp $bc to $target_method";;
+	    esac
+	    if ! in_barclamp "$bc" git rev-parse --quiet --verify \
+	        "${barclamp_targets[$bc:$target_branch]}" &>/dev/null; then
+	        if [[ $target = backup ]]; then
+		    debug "${barclamps[$bc:$target_branch]} in $bc has never been backed up, skipping."
+		    unset barclamp_targets[$bc:$target_branch]
+	        elif [[ $target = upstream ]]; then
+		    debug "Cannot reset barclamp $bc to ${barclamp_targets[$bc]}"
+		    unset barclamp_targets[$bc:$target_branch]
+	        fi
 	    fi
-	fi
-    done
-    for bc in "${!barclamp_targets[@]}"; do
-	in_barclamp "$bc" \
-	    reset_branch "$target_branch" "${barclamp_targets[$bc]}"
+        done
+        for bc in "${!barclamp_targets[@]}"; do
+	    in_barclamp "${bc%%:*}" \
+	        reset_branch "${bc#*:}" "${barclamp_targets[$bc]}"
+        done
     done
 }
 
