Make sync smart enough to handle basic branch swizzling in the Crowbar repo.

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -241,15 +241,29 @@ backup_everything() {
     fi
 }
 
+remote_branches_synced() {
+    # $1 = repository to operate in
+    # $2 = local branch to test
+    # $3 = remote branch to test
+    [[ -d $1/.git ]] || \
+	die "remote_branches_synced: $1 is not a git repo"
+    (cd "$1"; git rev-parse -q "$2") || \
+	die "remote_branches_synced: $2 does not resolve to a git commit"
+    (cd "$1"; git rev-parse -q "$3") || \
+	die "remote_branches_synced: $3 does not resolve to a git commit"
+    # $2 and $3 resolve to the same commit, they are in sync.
+    (cd "$1"; [[ $(git rev-parse "$2") = $(git rev-parse "$3") ]] ) && return 0
+    # Test to see if there are any commits in $3 that are not
+    # reachable from $2.  If there are, then the branches are not synced.
+    (cd "$1"; [[ ! $(git rev-list "$2..$3") ]] ) && return 0
+    return 1
+}
+
 sync_repo() (
     # $1 = dir to CD to initially.
     # Assumes that origin has already been fetched.
+    remote_branches_synced "$1" "master" "origin/master" && return 0
     cd "$1"
-    # master is the same as origin/master, nothing to merge.
-    [[ $(git rev-parse master) = $(git rev-parse origin/master) ]] && return 0
-    # Test to see if there are any commits in origin/master that do not
-    # exist in master.  If there are not, then we have no need to sync.
-    [[ $(git rev-list master..origin/master) ]] || return 0
     # Repo is not clean, we will refuse to merge in any case.
     git_is_clean || {
 	echo "$1 is not clean." >&2
@@ -303,17 +317,37 @@ sync_repo() (
 sync_everything() {
     local unsynced_barclamps=()
     local b head res=0
-    local thisdir="$PWD"
+    crowbar_is_clean || \
+	die "Will not try to sync local repo with origin when working tree is dirty."
     # Do barclamps first.
     for b in $(barclamps_in_branch ${DEV_REMOTE_BRANCHES["origin"]}); do
 	sync_repo "$CROWBAR_DIR/$b" && continue
 	unsynced_barclamps+=("$b")
     done
     # Finished with barclamps, now for crowbar.
-    sync_repo "$CROWBAR_DIR" || {
-	echo "Could not merge changes from origin into master branch of Crowbar." >&2
-	res=1
-    }
+    head=$(in_repo git symbolic-ref HEAD) || \
+	die "Could not save the current branch!"
+    if ! remote_branches_synced "$CROWBAR_DIR" master origin/master; then
+	if sync_repo "$CROWBAR_DIR"; then
+	    for b in ${DEV_REMOTE_BRANCHES["origin"]}; do
+		if ! remote_branches_synced "$CROWBAR_DIR" "$b" "origin/$b"
+		then
+		    in_repo git checkout "$b" ||
+		    in_repo git merge "origin/$b" || \
+			die "Merge origin/$b into $b branch of Crowbar failed."
+		fi
+	    done
+	fi
+    fi
+    for b in ${DEV_REMOTE_BRANCHES["origin"]}; do
+	if ! remote_branches_synced "$CROWBAR_DIR" "$b" "${DEV_BRANCHES[$b]}"
+	then
+	    in_repo git checkout "$b"
+	    in_repo git merge "${DEV_BRANCHES[$b]}" || \
+		die "Merge ${DEV_BRANCHES[$b]} into $b branch of Crowbar failed."
+	fi
+    done
+    in_reop git checkout "${head##*/}"
     if [[ $unsynced_barclamps ]]; then
 	echo "Unable to sync origin with current master in:" >&2
 	echo "  ${unsynced_barclamps[*]}"
@@ -360,6 +394,16 @@ Command line options:
 EOF
 }
 
+pull_requests_prep() {
+    crowbar_is_clean && fetch_all && sync_everything && backup_everything || \
+	die "Unable to prepare for pull requests"
+    local -A barclamps_to_push
+    local branch bc
+    for branch in ${DEV_REMOTE_BRANCHES["origin"]}; do
+	:
+    done
+}
+    
 case $1 in
     is_clean) crowbar_is_clean;;
     fetch) fetch_all;;
