When syncing, always save HEAD, and then restore it afterwards if needed.

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -857,6 +857,8 @@ sync_repo() (
     # Merge upstream branches from all remotes, but only if the branch
     # is listed in DEV_REMOTE_BRANCHES for that remote,
     # unless $remote is actually "origin"
+    [[ $head ]] || head=$(git symbolic-ref HEAD) || \
+        head=$(git rev_parse HEAD) || die "$repo: Cannot find head commit."
     while read ref branch; do
         branch=${branch#refs/heads/}
         for remote in "${!DEV_REMOTE_BRANCHES[@]}" personal; do
@@ -865,11 +867,10 @@ sync_repo() (
             sync_branch_from_personal "$remote" "$branch"
         done
     done < <(git show-ref --heads)
-    case $head in
-        refs/heads/*) git checkout -q "${head#refs/heads/}";;
-        '') : ;;
-        *) git checkout -q "${head}";;
-    esac
+    if [[ $(git rev-parse --verify -q HEAD) != \
+        $(git rev-parse --verify -q $head) ]]; then
+        git checkout -q "${head#refs/heads/}"
+    fi
 )
 
 # Recursivly merge all changes from a given branch into its children, if any.
@@ -883,11 +884,7 @@ ripple_changes_out() {
     for child in $(child_branches "$parent"); do
         in_repo git rev-parse --verify -q "$parent" &>/dev/null || \
             die "ripple_changes_out: $child is not a branch in Crowbar!"
-        debug "Testing $parent -> $child"
         branches_synced "$CROWBAR_DIR" "refs/heads/$child" "refs/heads/$parent" && continue
-        [[ $head ]] || head=$(in_repo git symbolic-ref HEAD) || \
-            die "Could not save the current branch!"
-        debug "Checking out $child"
         [[ $(in_repo git symbolic-ref HEAD) = refs/heads/$child ]] || \
             in_repo git checkout -q "$child"
         debug "Merging $parent into $child"
@@ -913,13 +910,18 @@ sync_everything() {
     done
     # Finished with barclamps, now for crowbar.
     debug "Syncing crowbar"
+    [[ $head ]] || head=$(git symbolic-ref HEAD) || \
+        head=$(git rev_parse HEAD) || die "$repo: Cannot find head commit."
     sync_repo "$CROWBAR_DIR" || \
         die "Could not sync Crowbar with origin branches"
     # Now for the branch-rippling merges of doom
     for branch in $(root_branches); do
         ripple_changes_out "$branch"
     done
-    [[ $head ]] && in_repo git checkout -q "${head#refs/heads/}"
+    if [[ $(git rev-parse --verify -q HEAD) != \
+        $(git rev-parse --verify -q $head) ]]; then
+        git checkout -q "${head#refs/heads/}"
+    fi
     if [[ $unsynced_barclamps ]]; then
         echo "Unable to sync origin with current master in:" >&2
         echo "  ${unsynced_barclamps[*]}"
