Add more advanced pull request handling.
dev now knows how to fetch open pull requests from repositories hosted
on Github, knows how to group pull request bundles, and knows
how to sort pull requests with the oldest first.

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -4,6 +4,9 @@ export LANG="C"
 export LC_ALL="C"
 
 GEM_RE='([^0-9].*)-([0-9].*)'
+PULL_BUNDLE_RE='Crowbar-Pull-ID: ([0-9a-f]{40})'
+PULL_RELEASE_RE='Crowbar-Release: ([^ ]+)'
+PULL_TITLE_RE='^(.*)\[([0-9]+)/([0-9]+)\]$'
 
 readonly currdir="$PWD"
 export PATH="$PATH:/sbin:/usr/sbin:/usr/local/sbin"
@@ -45,6 +48,7 @@ VERBOSE=true
     die "$CROWBAR_DIR is not a git checkout of Crowbar!"
 export CROWBAR_DIR
 [[ $CROWBAR_TEST_DIR ]] || export CROWBAR_TEST_DIR="/tmp/crowbar-dev-test"
+[[ $LOCAL_PULL_TRACKING ]] || LOCAL_PULL_TRACKING="$HOME/.crowbar/open_pull_requests"
 
 
 . "$CROWBAR_DIR/build_lib.sh" || exit 1
@@ -588,8 +592,310 @@ scrub_merged_pull_requests() {
     git remote prune personal
 }
 
+# Helper function only for use by fetch_pull_request_metadata
+save_pull_request_metadata() (
+    [[ $base_branch && \
+        $pull_req_branch && \
+        $pull_req_repo && \
+        $pull_req_sha && \
+        $repo && \
+        $title && \
+        $github_id && \
+        $created_at ]] || return
+    if [[ $pull_req_id ]]; then
+        local dest="$LOCAL_PULL_TRACKING/bundles/$pull_req_id/$repo"
+    else
+        local dest="$LOCAL_PULL_TRACKING/singletons/$repo/$github_id"
+        [[ $order ]] || order='1:1'
+    fi
+    mkdir -p "$dest" && cd "$dest"
+    echo "$order" > order
+    echo "$pull_req_repo" > repo
+    echo "$pull_req_branch" > source_branch
+    echo "$pull_req_sha" > source_sha
+    echo "$base_branch" > target_branch
+    echo "$github_id" > number
+    echo "$created_at" > created_at
+    echo "$title" > title
+    echo "$github_url" > github_url
+    [[ $updated_at ]] && echo "$updated_at" > updated_at
+    if [[ $rel ]]; then
+        echo "$rel" > release
+    else
+        echo "$(release_for_branch "$base_branch")" >release
+    fi
+)
+
+# Fetch pull request metadata from Github.
+# When this function is done, metadata for all pull requests generated by
+# dev for this repo will have the right metadata fragments in the tracking directory
+# for the repository in question.
+fetch_pull_request_metadata() {
+    # $1 = remote name
+    # $2 = repository name.
+
+    # Not a github remote?  Goodbye.
+    [[ ${DEV_REMOTE_URLBASE[$1]} =~ $github_re ]] || return 0
+    local acct="${BASH_REMATCH[2]}"
+    # Get our raw data.  This is what we in the business call fugly.
+    local -A pulls
+    . <(parse_yml_or_json - pulls < <(
+            curl_and_res "https://api.github.com/repos/$acct/$2/pulls"))
+    local pull_req_id pull_req_sha order pull_req_repo pull_req_branch created_at
+    local base_branch key ord repo title rel github_id updated_at github_url
+    for key in $(printf '%s\n' "${!pulls[@]}" |sort); do
+        if [[ $ord && $ord != ${key%%.*} ]]; then
+            # The first part of the key has changed, so we should have a complete set of data.
+            save_pull_request_metadata
+            unset pull_req_id pull_req_sha order pull_req_repo pull_req_branch created_at
+            unset base_branch key ord repo title rel github_id updated_at github_url
+
+            local pull_req_id pull_req_sha order pull_req_repo pull_req_branch created_at
+            local base_branch key ord repo title rel github_id updated_at github_url
+
+        fi
+        ord=${key%%.*}
+        # Strip off the inital array component of the hash key.
+        # We will not need it anyways.
+        case ${key#*.} in
+            body)
+                # If the body text does not have a pull request bundle ID, skip it.
+                [[ ${pulls[$key]} =~ $PULL_BUNDLE_RE ]] && pull_req_id="${BASH_REMATCH[1]}"
+                [[ ${pulls[$key]} =~ $PULL_RELEASE_RE ]] && rel="${BASH_REMATCH[1]}";;
+            # The repo and branch that contains changes to be tested.
+            head.ref) pull_req_branch="${pulls[$key]}";;
+            head.sha) pull_req_sha="${pulls[$key]}";;
+            head.repo.clone_url) pull_req_repo="${pulls[$key]}";;
+            title)
+                if [[ ${pulls[$key]} =~ $PULL_TITLE_RE ]]; then
+                    order="${BASH_REMATCH[2]}:${BASH_REMATCH[3]}"
+                    title="${BASH_REMATCH[1]}"
+                else
+                    title="${pulls[$key]}"
+                fi;;
+            base.ref) base_branch="${pulls[$key]}";;
+            base.repo.name) repo="${pulls[$key]}";;
+            number) github_id="${pulls[$key]}";;
+            created_at) created_at="${pulls[$key]}";;
+            updated_at) updated_at="${pulls[$key]}";;
+            html_url) github_url="${pulls[$key]}";;
+        esac
+    done
+    save_pull_request_metadata
+}
+
+fetch_pull_requests_for_remote() {
+    # $1 = remote to check for updates from
+    local remote
+    [[ $1 ]] && remote=$1 || remote=$(origin_remote)
+    crowbar_remote_exists "$remote" && remote_available "$remote" && \
+        [[ ${DEV_REMOTE_URLBASE[$remote]} =~ $github_re ]] || \
+        die "Cannot check for pull requests from $remote"
+    rm -rf "$LOCAL_PULL_TRACKING"
+    for bc in "$CROWBAR_DIR/barclamps/"*; do
+        [[ -d $bc/.git || -f $bc/.git ]] || continue
+        in_barclamp "${bc##*/}" git_remote_exists "$remote" || continue
+        debug "Fetching open pull requests for barclamp ${bc##*/}"
+        fetch_pull_request_metadata "$remote" "barclamp-${bc##*/}"
+    done
+    debug "Fetching open pull requests for Crowbar"
+    fetch_pull_request_metadata "$remote" "crowbar"
+    sort_pull_requests
+    debug "Done"
+}
+
+pull_request_bundle_sane() {
+    # $1 = bundle ID.
+    # Returns true if all components of the bundle are present, and if
+    # all the target branches in the barclamps match the release we are
+    # pulling against.
+    local -A orders releases branches
+    local -a order
+    local total_count=0 indicated_count=0 d f r repo o c release branch
+    local branch_for_release build bc
+    for d in "$LOCAL_PULL_TRACKING/bundles/$1/"*; do
+        [[ -d "$d" ]] || continue
+        repo="${d##*/}"
+        for f in order repo source_branch source_sha \
+            target_branch number created_at title release; do
+            [[ -f $d/$f ]] || return 1
+        done
+        read o < "$d/order"
+        read r < "$d/release"
+        read branch < "$d/target_branch"
+        if ((indicated_count == 0)); then
+            indicated_count="${o##*:}"
+        elif ((indicated_count != "${o##*:}")); then
+            debug "Indicated count changed for pull request bundle $1"
+            return 1
+        fi
+        if [[ ! $release ]]; then
+            release=$r
+            if ! release_exists "$release"; then
+                debug "Release $release does not exist locally."
+                return 1
+            fi
+        elif [[ $r != $release ]]; then
+            debug "Release changed in pull request bundle $1"
+            return 1
+        fi
+        if [[ $d = *barclamp-* ]]; then
+            bc="${d##barclamp-}"
+            for build in $(builds_for_barclamp_in_release "$bc" "$release"); do
+                [[ $branch = $(barclamp_branch_for_build "$build" "$bc") ]] && continue
+                debug "Branch $branch for barclamp $bc in bundle $1 does not match metadata."
+                return 1
+            done
+        fi
+        (   cd "$d"
+            [[ -f ../title ]] || cp title ..
+            [[ -f ../release ]] || cp release ..)
+        orders[$repo]=$o
+        releases[$repo]=$release
+        branches[$repo]=$branch
+        total_count=$(($total_count + 1))
+    done
+    if ((indicated_count != total_count)); then
+        debug "Not all barclamps in pull request bundle $1 at Github yet."
+    fi
+}
+
+show_open_pull_requests() {
+   local -a open_bundles open_singletons
+   local d r
+   for d in "$LOCAL_PULL_TRACKING/bundles/"*; do
+       [[ -d $d ]] || continue
+       pull_request_bundle_sane "${d##*/}" || continue
+       open_bundles+=("$d")
+   done
+   for d in "$LOCAL_PULL_TRACKING/singletons/"*/*; do
+       [[ -d $d ]] || continue
+       open_singletons+=("$d")
+   done
+   if (( ${#open_bundles[@]} == 0 && ${#open_singletons[@]} == 0)); then
+       r+="No open pull requests"
+   elif (( ${#open_bundles[@]} == 0 )); then
+       r+="${#open_singletons[@]} open singleton pull requests"
+   elif (( ${#open_singletons[@]} == 0)); then
+       r+="${#open_bundles[@]} open pull request bundles"
+   else
+       r+="${#open_bundles[@]} open pull request bundles and ${#open_singletons[@]} open singleton pull requests"
+   fi
+   debug "$r"
+}
+
+pull_request_last_touched() (
+    # $1 = bundle
+    # Returns the most recent date that any of the bundle components were touched.
+    local mtime
+    if [[ $1 = bundles/* ]]; then
+        cd "$LOCAL_PULL_TRACKING/$1" || die "Bundle $1 does not exist!"
+        for d in *; do
+            [[ -d $d ]] || continue
+            [[ $ltime ]] || read ltime <"$d/created_at"
+            [[ -f updated_at ]] && read $d/ltime <"$d/updated_at"
+            [[ $ltime > $mtime ]] && mtime=$ltime
+        done
+        echo $mtime
+    elif [[ $1 = singletons/* ]]; then
+        if [[ -f $LOCAL_PULL_TRACKING/$1/updated_at ]]; then
+            cat "$LOCAL_PULL_TRACKING/$1/updated_at"
+        else
+            cat "$LOCAL_PULL_TRACKING/$1/created_at"
+        fi
+    else
+        die "No idea how to find lat touched time for $1"
+    fi
+)
+
+pull_request_directories() (
+    cd "$LOCAL_PULL_TRACKING"
+    for d in bundles/* singletons/*/*; do
+        if [[ $d = bundles/* ]]; then
+            pull_request_bundle_sane "${d##*/}" || continue
+        fi
+        [[ -f $d/title ]] || continue
+        echo "$(pull_request_last_touched "$d")|$d"
+    done |sort |cut -d \| -f 2
+)
+
+
+sort_pull_requests() {
+    local count=1 p
+    rm "$LOCAL_PULL_TRACKING/pull_request_index" &>/dev/null
+    for p in $(pull_request_directories); do
+        echo "$count $p" >>"$LOCAL_PULL_TRACKING/pull_request_index"
+        count=$((count + 1))
+    done
+}
+
+show_pull_request() {
+    local idx id prq repo release
+    local -a builds
+    [[ $1 && $1 =~ [0-9]+ ]] || die "Please pass a pull request # from dev pull-request list!"
+    read idx id < <(grep "^$1 " "$LOCAL_PULL_TRACKING/pull_request_index")
+    [[ $1 = $idx ]] || die "$1 is not a valid pull request." \
+        "dev pull-requests list shows the open ones we know about."
+    prq="$LOCAL_PULL_TRACKING/$id"
+    [[ -f $prq/title ]] || die "Something Wicked happened trying to show $idx." \
+        "Please re-run dev pull-request fetch"
+    read release <"$prq/release"
+    if [[ $id = singletons/* ]]; then
+        repo="${id#singletons/}"
+        repo="${repo%/*}"
+        if [[ $repo = barclamp-* ]]; then
+            builds=($(builds_for_barclamp_in_release "${repo#barclamp-}" "$release"))
+        else
+            builds=($(builds_in_release "$release"))
+        fi
+        echo "Title:               $(cat "$prq/title")"
+        echo "Release:             $release"
+        echo "Last Updated:        $(pull_request_last_touched "$id")"
+        echo "Type:                singleton"
+        echo "Repo:                $repo"
+        echo "Repo with Changes:   $(cat "$prq/repo")"
+        echo "Branch with Changes: $(cat "$prq/source_branch")"
+        echo "Target Branch:       $(cat "$prq/target_branch")"
+        echo "Pull Request URL:    $(cat "$prq/github_url")"
+        echo "Builds:              ${builds[*]}"
+    elif [[ $id = bundles/* ]]; then
+        echo "Title:        $(cat "$prq/title")"
+        echo "Release:      $release"
+        echo "Last Updated: $(pull_request_last_touched "$id")"
+        echo "Type:         bundle"
+        echo "Bundle ID:    ${id##*/}"
+        local repo
+        for repo in "$prq/"*; do
+            [[ -d $repo ]] || continue
+            if [[ $repo = */barclamp-* ]]; then
+                builds=($(builds_for_barclamp_in_release "${repo#*/barclamp-}" "$release"))
+            else
+                builds=("all")
+            fi
+            echo "Repo: ${repo##*/}"
+            echo "    Repo with Changes:   $(cat "$repo/repo")"
+            echo "    Branch with Changes: $(cat "$repo/source_branch")"
+            echo "    Target Branch:       $(cat "$repo/target_branch")"
+            echo "    Pull Request URL:    $(cat "$repo/github_url")"
+            echo "    Builds:              ${builds[*]}"
+        done
+    else
+        die "Unknown pull request type $id!"
+    fi
+}
+
+list_pull_requests() {
+    local idx id
+    while read idx id; do
+        [[ -d $LOCAL_PULL_TRACKING/$id ]] || continue
+        cf="$LOCAL_PULL_TRACKING/$id/title"
+        cr="$LOCAL_PULL_TRACKING/$id/release"
+        echo "$idx: ($(cat "$cr")) $(cat "$cf")"
+    done <"$LOCAL_PULL_TRACKING/pull_request_index"
+}
+
 __fetch_all() {
-    local remote remotes=() res=true 
+    local remote remotes=() res=true
     if [[ $@ || $DEV_FROM_REMOTES ]]; then
 	[[ $1 ]] && remotes+=("$@")
 	[[ $DEV_FROM_REMOTES ]] && remotes+=("${DEV_FROM_REMOTES[@]}")
@@ -610,6 +916,12 @@ __fetch_all() {
 	if git fetch -q "$remote" &>/dev/null; then
             debug "  Fetched from $remote." 2>>"$results_dir/$logfile"
             printf '.'
+            if [[ $PWD = */barclamps/* ]]; then
+
+                fetch_pull_request_metadata "$remote" "barclamp-${PWD##*/}"
+            else
+                fetch_pull_request_metadata "$remote" "crowbar"
+            fi
         else
             debug "  Failed to fetch from $remote" 2>>"$results_dir/$logfile"
             printf '!'
@@ -624,6 +936,7 @@ __fetch_all() {
 # main Crowbar repository and the barclamps.
 fetch_all() {
     local results_dir d
+    [[ -d "$LOCAL_PULL_TRACKING" ]] && rm -rf "$LOCAL_PULL_TRACKING"
     results_dir="$(mktemp -d /tmp/crowbar_fetch_XXXXXX)" || \
         die "Cannot create temporary storage for fetch results!"
     debug "Fetching updates:"
@@ -645,6 +958,8 @@ fetch_all() {
     done
     rm -rf "$results_dir"
     update_all_tracking_branches
+    show_open_pull_requests
+    sort_pull_requests
 }
 
 # Attempt to scrub merged pull requests across all of the barclamps.
@@ -2437,12 +2752,11 @@ reload_unit_tests() (
       return 0
   fi
   reinstall_barclamps "${barclamps[@]}" || exit 1
-  BUNDLE=/var/lib/gems/1.8/bin/bundle
   if [[ $dbs_need_reload ]]; then
       cd "$CROWBAR_TEST_DIR/crowbar_framework"
       for rake_task in db:drop db:migrate db:fixtures:dump; do
           for RAILS_ENV in test development; do
-              (export RAILS_ENV; $BUNDLE exec rake "$rake_task")
+              (export RAILS_ENV; rake "$rake_task")
           done
       done
   fi
@@ -2611,6 +2925,21 @@ push_tag() {
     [[ $DRY_RUN = true ]] || in_repo git branch -D "tag-master-$1"
 }
 
+# Wrapper around common pull request functionality.
+pull_request_handler() {
+    local req=$1
+    shift
+    case $req in
+        fetch) fetch_pull_requests_for_remote "$@";;
+        prep) pull_requests_prep "$@";;
+        gen) pull_requests_gen "$@";;
+        dirs) pull_request_directories "$@";;
+        list) list_pull_requests "$@";;
+        show) show_pull_request "$@";;
+        '') show_open_pull_requests "$@";;
+    esac
+}
+
 # Hash for handling command -> function mapping.
 DEV_COMMANDS["backup"]="backup_everything"
 DEV_COMMANDS["barclamps-in-build"]="barclamps_in_build"
@@ -2628,6 +2957,7 @@ DEV_COMMANDS["current-build"]="current_build"
 DEV_COMMANDS["cut_release"]="cut_release"
 DEV_COMMANDS["erase-feature"]="erase_feature"
 DEV_COMMANDS["fetch"]="fetch_all"
+DEV_COMMANDS["fetch-pull-requests"]="fetch_pull_requests_for_remote"
 DEV_COMMANDS["find-parent"]="find_best_parent"
 DEV_COMMANDS["flatten"]="flatten_crowbar"
 DEV_COMMANDS["help"]="dev_help"
@@ -2637,6 +2967,7 @@ DEV_COMMANDS["missing-barclamps"]="find_missing_barclamps"
 DEV_COMMANDS["new-feature"]="cut_feature"
 DEV_COMMANDS["orphaned-barclamps"]="find_orphaned_barclamps"
 DEV_COMMANDS["pin"]="pin_release"
+DEV_COMMANDS["pull-requests"]="pull_request_handler"
 DEV_COMMANDS["pull-requests-gen"]="pull_requests_gen"
 DEV_COMMANDS["pull-requests-prep"]="pull_requests_prep"
 DEV_COMMANDS["purge-submodules"]="purge_submodule_metadata"
@@ -2678,6 +3009,7 @@ DEV_SHORT_HELP["current-build"]="      Shows the current build you are working o
 DEV_SHORT_HELP["cut_release"]="        Cut a new release from the current one."
 DEV_SHORT_HELP["erase-feature"]="      Forget about branches for a feature you are not working on."
 DEV_SHORT_HELP["fetch"]="              Fetch updates from configured upstream repositories."
+DEV_SHORT_HELP["fetch-pull-requests"]="Fetch pull request information from a specific remote"
 DEV_SHORT_HELP["find-parent"]="        Find the closest parent of a release or feature."
 DEV_SHORT_HELP["flatten"]="            Flatten the main Crowbar repo branching structure."
 DEV_SHORT_HELP["help"]="               Show detailed help."
@@ -2687,6 +3019,7 @@ DEV_SHORT_HELP["missing-barclamps"]="  Show missing barclamps."
 DEV_SHORT_HELP["new-feature"]="        Create a new feature bundle from the current release."
 DEV_SHORT_HELP["orphaned-barclamps"]=" Show barclamps that are not part of any build."
 DEV_SHORT_HELP["pin"]="                Pin a release, build, or barclamp in a build to a specific rev"
+DEV_SHORT_HELP["pull-requests"]="      Manage creating, testing, and merging pull requests"
 DEV_SHORT_HELP["pull-requests-gen"]="  Issue pull requests."
 DEV_SHORT_HELP["pull-requests-prep"]=" Prepare to issue pull requests."
 DEV_SHORT_HELP["purge-submodules"]="   Purge submodule information for the master branch in Crowbar."
@@ -2979,6 +3312,8 @@ DEV_LONG_HELP["push-tag"]="Pushes a tagged release to specified remotes.
   The tagged release must have been created with tag-build.
   First argument must be the tag created with tag-build, and the remotes to push to
   must be passed explicitly with --to."
+DEV_LONG_HELP["fetch-pull-requests"]="Fetch pull request metadata from a remote"
+DEV_LONG_HELP["pull-requests"]="Manage pull requests"
 
 
 # Verify that we have help for all commands, and exit if we don't.
