Teach dev to do some basic remote management.
This inccludes adding, removing, modifying, and fetching from remotes
other than the ones that dev inplicitly knows about.

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -422,33 +422,43 @@ update_all_tracking_branches() {
 # Fetch (but do not merge) updates from all our remotes, in both the
 # main Crowbar repository and the barclamps.
 fetch_all() {
-    local remote barclamp b
+    local remote remotes=() barclamp b branches=()
     dev_is_setup
-    for remote in "${DEV_REMOTES[@]}" personal; do
+    if [[ $@ ]]; then
+        remotes=("$@")
+    else
+        remotes=("${DEV_REMOTES[@]}" personal)
+    fi
+    for remote in "${remotes[@]}"; do
         in_repo git_config_has "remote.$remote.url" || continue
         debug "Fetching from remote $remote:"
         debug "    Crowbar"
         in_repo git fetch -q "$remote" || continue
-        in_repo update_tracking_branches "$remote"
-        local -A touched_barclamps
-        for b in $(filter_branches_for_remote "$remote" \
-            $(all_ordered_branches)); do
-            for barclamp in $(barclamps_from_branch "$b"); do
-                [[ ${touched_barclamps[$barclamp]} ]] && continue
-                debug "    Barclamp $barclamp"
-                if in_barclamp "$barclamp" git_config_has 'remote.personal.url'; then
-                    in_barclamp "$barclamp" \
-                        git fetch -q --multiple origin personal || \
-                    die "Could not fetch updates for $barclamp"
-                else
+        branches=($(filter_branches_for_remote "$remote" \
+            $(all_ordered_branches)))
+        if [[ ${branches[@]} ]]; then
+            in_repo update_tracking_branches "$remote"
+            local -A touched_barclamps
+            for b in "${branches[@]}"; do
+                for barclamp in $(barclamps_from_branch "$b"); do
+                    [[ ${touched_barclamps[$barclamp]} ]] && continue
+                    debug "    Barclamp $barclamp"
                     in_barclamp "$barclamp" git fetch -q origin || \
-                    die "Could not fetch updates for $barclamp"
-                fi
-                in_barclamp "$barclamp" update_tracking_branches origin
-                touched_barclamps[$barclamp]="true"
+                        die "Could not fetch updates for $barclamp"
+                    in_barclamp "$barclamp" update_tracking_branches origin
+                    touched_barclamps[$barclamp]="true"
+                done
             done
-        done
-        unset touched_barclamps
+            unset touched_barclamps
+        else
+            for barclamp in "$CROWBAR_DIR/barclamps/"*; do
+                [[ -d $barclamp ]] || continue
+                (   cd "$barclamp"
+                    git_config_has "remote.${remote}.url" || continue
+                    debug "    Barclamp ${barclamp##*/}"
+                    git fetch "$remote")
+            done
+        fi
     done
 }
 
@@ -495,6 +505,91 @@ github_url() {
 }
 
 git_config_has() { git config --get "$1" &>/dev/null; }
+
+get_repo_name() {
+    local repo
+    repo="$(git config --get remote.origin.url)" || \
+        die "$PWD: Could not get the URL for the origin remote for this repo."
+    repo="${repo##*:}"
+    echo "${repo##*/}"
+}
+
+add_remote() {
+    # $1 = name of the remote to add.
+    # $2 = base part of the repo to add.
+    git_config_has "remote.$1.url" && return 0
+    local repo
+    repo="$(get_repo_name)" || exit 1
+    repo="$2/$repo"
+    git ls-remote "$repo" refs/heads/master &>/dev/null || {
+        debug "No git repo at $repo, skipping."
+        return 0
+    }
+    git remote add "$1" "$repo"
+    git fetch "$1"
+}
+
+rm_remote() {
+    git_config_has "remote.$1.url" || return 0
+    git remote rm "$1"
+}
+
+set_url_remote() {
+    git_config_has "remote.$1.url" || return 0
+    local repo
+    repo="$(get_repo_name)" || exit 1
+    repo="$2/$repo"
+    git ls-remote "$repo" refs/heads/master &>/dev/null || {
+        debug "No git repo at $repo, skipping."
+        return 0
+    }
+    git set-url "$1" "$repo"
+}
+
+show_remote() {
+    if [[ $1 ]]; then
+        git remote show "$1"
+    else
+        git remote show
+    fi
+}
+
+remote_wrapper() {
+    # $1 = one of "add", "rm", "set-url", "show"
+    # $2 = name of remote
+    # $3 = base part of the remote URL.  Only used for add and set-url.
+    local remote urlbase action bc
+    remote="$2"
+    urlbase="$3"
+    case $1 in
+        add) action=add_remote
+            if ! in_repo \
+                git_config_has "crowbar.remote.${remote}.urlbase"; then
+                in_repo git config "crowbar.remote.${remote}.urlbase" "$3"
+            fi;;
+        rm) action=rm_remote
+            if in_repo git_config_has "crowbar.remote.${remote}.urlbase"; then
+                in_repo git config --unset "crowbar.remote.${remote}.urlbase"
+            fi
+;;
+        set-url) action=set_url_remote
+            if in_repo git_config_has "crowbar.remote.${remote}.urlbase"; then
+                in_repo git config "crowbar.remote.${remote}.urlbase" "$3"
+            else
+                die "Cannot set-url for a remote your have not added."
+            fi;;
+        show) action=show_remote;;
+        ''|help) die "Please pass one of add, rm, set-url, or show.";;
+        *) die "Unknown action $1 for remote.";;
+    esac
+    for bc in "$CROWBAR_DIR/barclamps/"*; do
+        [[ -d $bc ]] || continue
+        debug "Barclamp: ${bc##*/}"
+        in_barclamp "${bc##*/}" $action "$remote" "$urlbase"
+    done
+    debug "Crowbar:"
+    in_repo $action "$remote" "$urlbase"
+}
 
 # Perform initial setup.  If you make any changes to this function, take
 # care to make sure it stays idempotent.
@@ -1038,6 +1133,25 @@ Command line options:
            Does not try to merge any changes into your local repository.
            You can run a fetch at any time without disturbing your working
            code, provided you have network connectivity.
+           If you pass the name of a remote, fetch will try to fetch changes
+           from that remote in the main Crowbar repository and in each of the 
+           barclamps
+
+  remote -- Manage remotes across all dellcloudedge repositories.  It has the
+            following subcommands:
+            add <remote> <urlbase> : The add subcommand adds a new remote to
+                the Crowbar repositories.  
+            rm <remote> : The rm subcommand removes an already-existing remote
+                from the Crowbar repositories.
+            set-url <remote> <urlbase> : The set-url subcommands allows you to
+                give an existing remote a new URL in all the subrepositories.
+            show <remote> : The show subcommand shows remote information for
+                the named remote in all the Crowbar repositories.
+
+           Note that <urlbase> is the URL got will use without the actual
+           repository name.  dev assumes that the new remote uses the same
+           repository name as the origin remote does, and things will fail
+           badly if this assumption is violated.
 
   backup -- Push any locally committed changes in any repositories that were
             initially forked from dellcloudedge into your personal Github forks.
@@ -1570,7 +1684,7 @@ build_crowbar() {
 
 case $1 in
     is_clean) shift; crowbar_is_clean "$@";;
-    fetch) fetch_all;;
+    fetch) shift; fetch_all "$@";;
     sync) sync_everything;;
     setup) setup;;
     backup) backup_everything;;
@@ -1587,6 +1701,7 @@ case $1 in
     checkout) shift; checkout "$@";;
     build) shift; build_crowbar "$@";;
     show-repos) show_github_repos;;
+    remote) shift; remote_wrapper "$@";;
     erase-feature) shift; erase_release "feature/$1";;
     *) dev_help ; die "Unknown command $1.  Please use \"help\" for help.";;
 esac
